# Tensor Operations

## Basic Info

In [6]:
import torch
t = torch.tensor([1, 2, 3])
t
t.shape
t.size()
t.numel()
t.ndim

1

## Relation between origin, cloned, detached and device

In [7]:
if torch.cuda.is_available():
    t = t.to("cuda")
t.device

device(type='cuda', index=0)

In [8]:
print(t)
t.requires_grad
td = t.detach()
tc = td.cpu()
tn = tc.clone()
print(td, tc, tn)

tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3], device='cuda:0') tensor([1, 2, 3]) tensor([1, 2, 3])


In [9]:
td[0] = 0
print(t, td, tc, tn)

tensor([0, 2, 3], device='cuda:0') tensor([0, 2, 3], device='cuda:0') tensor([1, 2, 3]) tensor([1, 2, 3])


In [10]:
tc[1] = 0
print(t, td, tc, tn)

tensor([0, 2, 3], device='cuda:0') tensor([0, 2, 3], device='cuda:0') tensor([1, 0, 3]) tensor([1, 2, 3])


## Tensor Init

In [14]:
from torch import Tensor, randn, zeros, ones, diag
print("Tensor: ", Tensor([1, 2, 3]))
print("randn: ", randn(2, 2))
print("zeros: ", zeros(2, 2))
print("ones: ", ones(2, 2))
print("diag: ", diag([1, 2, 3]))

Tensor:  tensor([1., 2., 3.])
randn:  tensor([[ 1.0360, -1.4552],
        [-1.1492, -0.4673]])
zeros:  tensor([[0., 0.],
        [0., 0.]])
ones:  tensor([[1., 1.],
        [1., 1.]])


TypeError: diag(): argument 'input' (position 1) must be Tensor, not list

## Tensor Operations

In [ ]:
import torch
A = torch.Tensor([1, 2, 3])